/**
 * animeiAPI – Express Scraper API
 * Generated by @zjkm666/scraperapi
 * Source: https://www.miruro.tv/, https://www.miruro.ru/, https://www.miruro.bz/, https://www.miruro.to/
 *
 * Run:
 *   npm install
 *   npm run dev   # http://localhost:3000
 *
 * Customize:
 *   Edit api.config.js to add GET/POST endpoints.
 */
require('dotenv').config();
const express = require('express');
const cors = require('cors');
const NodeCache = require('node-cache');
const config = require('./api.config');
const { scrape, anilist, mirrorPipe, pipe, pipeFirstWorking, proxyHls, b64DecodeUrl } = require('./scraper');

const app = express();
const PORT = process.env.PORT || 3000;

// ── Middleware ───────────────────────────────────────────────────────
app.use(cors());
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true }));

// simple logger
app.use((req, _res, next) => {
  console.log(`${new Date().toISOString()} ${req.method} ${req.path}`);
  next();
});

// ── Cache (optional) ─────────────────────────────────────────────────
const cacheEnabled = !!(config.cache && (config.cache.enabled !== false));
const cacheTtl = (config.cache && config.cache.ttl) || 300;
const cache = cacheEnabled ? new NodeCache({ stdTTL: cacheTtl, checkperiod: 60, useClones: false }) : null;

function stableStringify(value) {
  if (value == null) return 'null';
  if (typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  return `{${Object.keys(value)
    .sort()
    .map((k) => `${JSON.stringify(k)}:${stableStringify(value[k])}`)
    .join(',')}}`;
}

function cacheKeyFor(endpoint, url, req) {
  // include body/query for POST/GET variance
  const extra = endpoint.method?.toUpperCase() === 'POST' ? req.body : req.query;
  try {
    return `${endpoint.method}:${endpoint.path}:${url}::${stableStringify(extra || {})}`;
  } catch {
    return `${endpoint.method}:${endpoint.path}:${url}`;
  }
}

function isCacheEnabledFor(endpoint) {
  if (!cacheEnabled || !cache) return false;
  if (endpoint.cache === false) return false;
  if (endpoint.cache === true) return true;
  if (endpoint.cache && typeof endpoint.cache === 'object' && endpoint.cache.enabled === false) return false;
  return true;
}

function getTtlFor(endpoint) {
  if (endpoint.cache && typeof endpoint.cache === 'object' && endpoint.cache.ttl) return Number(endpoint.cache.ttl);
  return undefined;
}

// ── Helpers ──────────────────────────────────────────────────────────
function sourceUrls() {
  const src = process.env.SOURCE_URL || config.sourceUrl;
  let list;
  if (Array.isArray(src)) {
    list = src;
  } else if (typeof src === 'string') {
    list = src.includes(',') ? src.split(',') : [src];
  } else {
    list = [];
  }
  return list
    .map((s) => (s ? String(s).trim().replace(/\/+$/, '') : ''))
    .filter((s) => /^https?:\/\//.test(s));
}

function resolveUrl(endpoint, req) {
  const urls = sourceUrls();
  const override = req.query?.source || req.body?.source;
  const base =
    (override && urls.find((u) => u.includes(override.replace(/\/+$/, '')) || u.startsWith(override))) ||
    urls[0] ||
    '';
  if (typeof endpoint.buildUrl === 'function') {
    const built = endpoint.buildUrl(base, req);
    if (typeof built !== 'string' || !built.trim()) throw new Error('buildUrl must return a string URL');
    return built.trim();
  }
  if (typeof endpoint.buildUrl === 'string') {
    // string template with :param placeholders, e.g. "/product/:id"
    let url = endpoint.buildUrl;
    // replace :param from body/query/params
    const params = { ...(req.params || {}), ...(req.query || {}), ...(req.body || {}) };
    for (const [k, v] of Object.entries(params)) {
      url = url.replaceAll(`:${k}`, encodeURIComponent(String(v)));
    }
    if (url.startsWith('/')) return base + url;
    return url;
  }
  if (endpoint.url) {
    // deprecated alias for buildUrl string
    return endpoint.url.startsWith('http') ? endpoint.url : base + endpoint.url;
  }
  return base + (endpoint.pathSuffix || '');
}

function validateConfig() {
  if (sourceUrls().length === 0) {
    throw new Error('api.config.js: sourceUrl must be a valid http(s) URL (or array of URLs)');
  }
  if (!Array.isArray(config.endpoints) || config.endpoints.length === 0) {
    console.warn('⚠ api.config.js: no endpoints defined. Add entries to config.endpoints.');
  }
}

// ── Auto-register endpoints from config ──────────────────────────────
function registerEndpoints() {
  for (const ep of config.endpoints) {
    const method = (ep.method || 'GET').toLowerCase();
    if (!['get', 'post'].includes(method)) {
      console.warn(`Skipping endpoint with unsupported method: ${ep.method} ${ep.path}`);
      continue;
    }

    app[method](ep.path, async (req, res) => {
      const start = Date.now();
      let targetUrl;
      try {
        targetUrl = resolveUrl(ep, req);
      } catch (e) {
        return res.status(400).json({ success: false, error: e.message });
      }

      const useCache = isCacheEnabledFor(ep);
      const cacheKey = useCache ? cacheKeyFor(ep, targetUrl, req) : null;

      if (useCache) {
        const hit = cache.get(cacheKey);
        if (hit) {
          res.set('X-Cache', 'HIT');
          return res.json({ success: true, cached: true, source: targetUrl, data: hit, tookMs: Date.now() - start });
        }
      }

      try {
        // merge params/query/body into a single opts bag for build* callbacks
        const opts = {
          ...(req.params || {}),
          ...(req.query || {}),
          ...(req.body || {}),
        };

        let data;
        if (ep.kind === 'anilist') {
          const { query, variables } = ep.buildQuery(opts);
          data = await anilist(query, variables);
          if (typeof ep.map === 'function') data = ep.map(data);
        } else if (ep.kind === 'pipe') {
          const first = targetUrl.replace(/\/+$/, '');
          const bases = [first, ...sourceUrls().filter((u) => u !== first)];
          const fanOut = (b, p) => pipeFirstWorking(bases.includes(b) ? bases : [b, ...bases], p);
          const resolved = await ep.buildPayload(opts, first, req);
          if (typeof ep.resolve === 'function') {
            const helpers = { pipe: fanOut, mirrorPipe };
            data = await ep.resolve(resolved, helpers);
          } else {
            data = await pipeFirstWorking(bases, resolved);
          }
        } else {
          // kind === 'json' or legacy HTML scraping
          data = await scrape({
            url: targetUrl,
            kind: ep.kind,
            buildQuery: ep.buildQuery,
            buildPayload: ep.buildPayload,
          });
          if (typeof ep.map === 'function') data = ep.map(data);
        }

        if (useCache) {
          const ttl = getTtlFor(ep);
          if (ttl) cache.set(cacheKey, data, ttl);
          else cache.set(cacheKey, data);
          res.set('X-Cache', 'MISS');
        }

        res.json({
          success: true,
          cached: false,
          source: targetUrl,
          count: Array.isArray(data) ? data.length : data ? 1 : 0,
          data,
          tookMs: Date.now() - start,
        });
      } catch (err) {
        console.error(`[${ep.method} ${ep.path}] failed:`, err.message);
        const status = err.status && err.status < 500 ? err.status : 502;
        res.status(status).json({
          success: false,
          error: 'Request failed',
          details: err.message,
          source: targetUrl,
        });
      }
    });

    console.log(`  ↳ ${method.toUpperCase().padEnd(4)} ${ep.path}  →  ${ep.kind || 'html'}`);
  }
}

// ── Health / meta ────────────────────────────────────────────────────
app.get('/', (_req, res) => {
  res.json({
    name: config.name,
    sourceUrl: sourceUrls(),
    endpoints: config.endpoints.map((e) => ({
      method: e.method,
      path: e.path,
      kind: e.kind || 'html',
      description: e.description || '',
    })),
    cache: cacheEnabled ? { enabled: true, ttl: cacheTtl, keys: cache.keys().length } : { enabled: false },
    docs: 'Edit api.config.js to customize GET/POST endpoints. Restart server after changes.',
  });
});

app.get('/health', (_req, res) => res.json({ status: 'ok', uptime: process.uptime() }));

app.get('/cache/stats', (_req, res) => {
  if (!cache) return res.json({ enabled: false });
  res.json({ enabled: true, ...cache.getStats(), keys: cache.keys().length });
});

app.delete('/cache', (_req, res) => {
  if (!cache) return res.json({ enabled: false, message: 'Cache disabled' });
  cache.flushAll();
  res.json({ success: true, message: 'Cache cleared' });
});

// ── HLS proxy ─────────────────────────────────────────────────────────
// /hls/:base64url(targetUrl) → fetch (with Referer) + rewrite m3u8 segments.
app.get('/hls/:encoded', async (req, res) => {
  try {
    const targetUrl = b64DecodeUrl(req.params.encoded);
    const refererBase = process.env.HLS_REFERER || sourceUrls()[0] || 'https://www.miruro.tv';
    const selfUrl = process.env.HLS_ORIGIN || `${req.protocol}://${req.get('host')}`;
    const { body, contentType } = await proxyHls(targetUrl, { refererBase, selfUrl });
    res.set('Content-Type', contentType);
    res.set('Cache-Control', 'public, max-age=3600');
    res.set('Access-Control-Allow-Origin', '*');
    if (Buffer.isBuffer(body)) return res.send(body);
    return res.send(body);
  } catch (err) {
    const status = err.status && err.status < 500 ? err.status : 502;
    res.status(status).json({ success: false, error: 'HLS proxy failed', details: err.message });
  }
});

// ── Boot ─────────────────────────────────────────────────────────────
validateConfig();
registerEndpoints();

// 404 – must be after registerEndpoints
app.use((req, res) => {
  res.status(404).json({
    success: false,
    error: 'Not found',
    available: config.endpoints.map((e) => `${e.method} ${e.path}`).concat(['GET /', 'GET /health', 'GET /hls/:encodedUrl']),
  });
});

if (require.main === module) {
  app.listen(PORT, '0.0.0.0', () => {
    console.log(`\n  🚀 animeiAPI running at http://localhost:${PORT}`);
    console.log(`     Source: ${sourceUrls().join(', ')}`);
    console.log(`     Cache : ${cacheEnabled ? `enabled (TTL ${cacheTtl}s)` : 'disabled'}`);
    console.log(`     Try   : curl http://localhost:${PORT}${config.endpoints[0]?.path || '/search'}\n`);
  });
}

module.exports = app;
