FROM node:18-slim
WORKDIR /app
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/consumet/api.consumet.org.git . && npm install
EXPOSE 3000
CMD ["npm", "start"]
